import React, { useState } from 'react';

export const Footer = () => {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <footer className="border-t border-border-hairline bg-off-white">
            <div className="border-b border-border-hairline">
                <button 
                    className="w-full flex items-center justify-between px-8 lg:px-16 py-6 bg-off-white hover:bg-gray-50 transition-colors group text-left focus:outline-none"
                    onClick={() => setIsOpen(!isOpen)}
                >
                    <div className="flex items-center gap-3">
                        <span className="material-symbols-outlined text-[16px] text-charcoal group-hover:text-charcoal-muted">library_books</span>
                        <h4 className="text-[10px] font-bold uppercase tracking-widest text-charcoal group-hover:text-charcoal-muted transition-colors">Cited Sources (28)</h4>
                    </div>
                    <span className={`material-symbols-outlined text-charcoal text-lg group-hover:text-charcoal-muted transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}>
                        expand_more
                    </span>
                </button>
                
                <div className={`overflow-hidden transition-all duration-500 ease-in-out bg-white ${isOpen ? 'max-h-[800px] border-t border-border-hairline' : 'max-h-0'}`}>
                    <div className="px-8 lg:px-16 py-12 max-w-7xl mx-auto">
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                            <SourceColumn 
                                items={[
                                    { id: "01", category: "Market", desc: "\"The State of AI in SaaS 2024\" - Gartner Analysis Report" },
                                    { id: "02", category: "Finance", desc: "Series B Valuation Multiples for GenAI Verticals - Pitchbook" }
                                ]} 
                            />
                            <SourceColumn 
                                items={[
                                    { id: "05", category: "Tech", desc: "NVIDIA H100 Availability & Pricing Forecast Q4" },
                                    { id: "12", category: "Legal", desc: "EU AI Act: Compliance Checklist for Generative Models" }
                                ]} 
                            />
                            <SourceColumn 
                                items={[
                                    { id: "28", category: "Comp", desc: "OpenAI Enterprise vs. Custom LLM TCO Analysis" }
                                ]} 
                            />
                        </div>
                    </div>
                </div>
            </div>
            
            <div className="px-8 lg:px-16 py-16">
                <div className="max-w-7xl mx-auto">
                    <h4 className="text-[10px] font-bold uppercase tracking-widest text-charcoal mb-8">Footnotes & References</h4>
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 text-[10px] text-charcoal-muted font-mono leading-relaxed">
                        <ol className="list-decimal list-inside space-y-2">
                            <li>Generated by Agent Alpha. Timestamp: 2024-02-05T10:07:51.289Z.</li>
                            <li>Model Version: Syndicate-Pro-Vision-X v4.2.</li>
                            <li>Data Source: Internal Audit Logs & Gartner SaaS Reports 2023-24.</li>
                            <li>Risk Scoring Methodology: NIST SP 800-30 Rev. 1 Guide for Conducting Risk Assessments.</li>
                        </ol>
                        <ol className="list-decimal list-inside space-y-2 start-[5]">
                            <li value={5}>ROI Calculation: (Net Profit / Cost of Investment) x 100. Assumes 5% churn rate.</li>
                            <li>Legal Disclaimer: This document contains forward-looking statements and is for internal use only.</li>
                            <li>Compliance Status: Verified by third-party auditor (Deloitte) on Jan 15, 2024.</li>
                        </ol>
                    </div>
                    <div className="mt-12 pt-8 border-t border-border-hairline flex justify-between items-center">
                        <span className="text-[9px] font-bold uppercase tracking-widest text-charcoal-muted">© 2024 Syndicate Inc.</span>
                        <span className="text-[9px] font-bold uppercase tracking-widest text-charcoal-muted">Confidential</span>
                    </div>
                </div>
            </div>
        </footer>
    );
};

const SourceColumn = ({ items }: { items: {id: string, category: string, desc: string}[] }) => (
    <div className="space-y-6">
        {items.map((item, idx) => (
            <div key={idx} className="group cursor-pointer">
                <div className="flex justify-between items-baseline mb-1 border-b border-dashed border-border-hairline pb-1">
                    <span className="text-[9px] font-mono font-bold text-charcoal">{item.id}</span>
                    <span className="text-[9px] text-charcoal-muted uppercase">{item.category}</span>
                </div>
                <p className="text-[10px] leading-relaxed text-charcoal-muted group-hover:text-charcoal transition-colors font-serif mt-2">
                    {item.desc}
                </p>
            </div>
        ))}
    </div>
);